#!/bin/bash

set -e

cd -- "$(dirname -- "$0")"

export PATH=$PWD:$PATH

projects/signature/signaturetohtml
projects/bashoneliners/bashonelinerstohtml

exec >index.html

cat <<EOD
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Paul Beard</title>
        <style>
            body { font-family: sans-serif; }
            a { text-decoration: inherit; color: inherit; }
            pre { white-space: pre-wrap; font-family: monospace; color: #000000; background-color: #ffffff; }
EOD
cat projects/*/vim.css | sort -u | sed '/^ *$/!s/^/            /'
cat <<EOD
        </style>
    </head>
    <body>
        <h1 style="text-align: center; font-weight: normal; font-size: 2em;">
            <span style="text-transform: lowercase;">The website of</span><br/>
            <span style="font-size: 1.3em;">Paul Beard</span>
        </h1>

        <p style="text-align: center;">
            <a href="mailto:web@paulbeard.name"><span style="font-weight: bold;">Email</span> web@paulbeard.name</a><br/>
            <a href="https://www.linkedin.com/in/paulsbeard/" target="_blank"><span style="font-weight: bold;">LinkedIn</span> https://www.linkedin.com/in/paulsbeard/</a><br/>
            <a href="https://github.com/paulbearddotname" target="_blank"><span style="font-weight: bold;">GitHub</span> https://github.com/paulbearddotname</a>
        </p>

EOD
sed '/<pre>/,/<\/pre>/!{/^ *$/!s/^/        /;}' projects/signature/pre.html

find projects -mindepth 1 -maxdepth 1 -type d | sort | while read -r PROJECT
do
    if [[ ! -e "$PROJECT"/index.html ]]
    then
        continue
    fi

    echo
    sed '/<pre>/,/<\/pre>/!{/^ *$/!s/^/        /;}' "$PROJECT"/index.html

    if [[ -e "$PROJECT"/pre.html ]]
    then
        echo
        sed '/<pre>/,/<\/pre>/!{/^ *$/!s/^/        /;}' "$PROJECT"/pre.html
    fi

    if [[ -e "$PROJECT"/screenshots ]]
    then
        cat <<EOD

        <p>
EOD
        find "$PROJECT"/screenshots -type f -not -name .\* | sort | while read -r SCREENSHOT
        do
        cat <<EOD
            <img src="$SCREENSHOT" alt="$(basename -- "$SCREENSHOT")"/>
EOD
        done
        cat <<EOD
        </p>
EOD
    fi

    if [[ -e "$PROJECT"/downloads ]]
    then
        cat <<EOD

        <p>
EOD
        find "$PROJECT"/downloads -type f -not -name .\* | sort | while read -r DOWNLOAD
        do
        cat <<EOD
            <a href="$DOWNLOAD">$(basename -- "$DOWNLOAD")</a><br/>
EOD
        done
        cat <<EOD
        </p>
EOD
    fi

done

cat <<EOD
    </body>
</html>
EOD
