#!/bin/bash

set -e
set -o pipefail

cd -- "$(dirname -- "$0")"

export PATH=${PWD:?}:$PATH

projects/signature/signaturetohtml
projects/bashoneliners/bashonelinerstohtml

exec >index.html

cat <<EOD
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Paul's website</title>
        <style>
            body { font-family: sans-serif; }
            h1, h2 { font-weight: normal; }
            a { text-decoration: inherit; color: inherit; }
            pre { white-space: pre-wrap; font-family: monospace; color: #000000; background-color: #ffffff; }
EOD
cat projects/*/vim.css | sort -u | sed '/^ *$/!s/^/            /'
cat <<EOD
        </style>
    </head>
    <body>
        <div style="display: flex; flex-wrap: wrap;">
            <h1 style="flex: auto; white-space: nowrap;">Paul's website</h1>

            <p style="flex: none;">
                <a href="mailto:web@paulbeard.name">web@paulbeard.name</a><br>
                <a href="https://github.com/paulbearddotname" target="_blank">github.com/paulbearddotname</a>
            </p>
        </div>
EOD

cat projects/signature/comment.html projects/signature/pre.html

find projects -mindepth 1 -maxdepth 1 -type d | sort | while read -r PROJECT
do
    if [[ ! -e "${PROJECT:?}"/index.html ]]
    then
        continue
    fi

    echo
    sed '/<pre>/,/<\/pre>/!{/^ *$/!s/^/        /;}' "${PROJECT:?}"/index.html

    if [[ -e "${PROJECT:?}"/pre.html ]]
    then
        echo
        sed '/<pre>/,/<\/pre>/!{/^ *$/!s/^/        /;}' "${PROJECT:?}"/pre.html
    fi

    if [[ -e "${PROJECT:?}"/screenshots ]]
    then
        cat <<EOD

        <p>
EOD
        find -- "${PROJECT:?}"/screenshots -type f -not -name .\* | sort | while read -r SCREENSHOT
        do
        cat <<EOD
            <img src="${SCREENSHOT:?}" alt="$(basename -- "${SCREENSHOT:?}")"/>
EOD
        done
        cat <<EOD
        </p>
EOD
    fi

    if [[ -e "${PROJECT:?}"/downloads ]]
    then
        cat <<EOD

        <p>
            Download
EOD
        find -- "${PROJECT:?}"/downloads -type f -not -name .\* | sort | while read -r DOWNLOAD
        do
        cat <<EOD
            <a href="${DOWNLOAD:?}">$(basename -- "${DOWNLOAD:?}")</a>
EOD
        done
        cat <<EOD
        </p>
EOD
    fi

done

cat <<EOD
    </body>
</html>
EOD
