#!/bin/bash

set -e

cd -- "$(dirname -- "$0")"

tohtml signature.c

sed -n '/^<style/,/^<\/style>/{/^\./p;}' signature.c.html >vim.css
sed -nE '/^<pre/,/^<\/pre>/{s/<pre id='\'vimCodeElement\''>/<pre>/;s/<span id="L[0-9]+" class="LineNr"> *[0-9]+ <\/span>//;p;}' signature.c.html >pre.html

rm signature.c.html
